const test=require("node:test"),assert=require("node:assert/strict");
const { battleEvidence,listConfigs,loadConfig }=require("../lib/official-config-catalog");
const { catalogSummary,initialState,reduceState }=require("../lib/universal-system-service");
const payments=require("../lib/sandbox-payment-service");

test("latest decrypted client catalog and battle oracle are active with legacy fallback",()=>{assert(listConfigs().length>1_400);assert.equal(Object.keys(loadConfig("SkillBuff").table).length,4429);assert.equal(loadConfig("Item").file.includes("1.201.01"),true);assert.equal(loadConfig("StageIdle").file.includes("data\\official\\client-full"),true);const evidence=battleEvidence();assert.equal(evidence.client_version,"1.201.01.360409");assert(evidence.bytes>11_000_000);assert.match(evidence.sha256,/^[a-f0-9]{64}$/)});
test("all classic and 1.201 HD protobuf modules have an implementation route",()=>{const catalog=catalogSummary();assert.equal(catalog.module_count,241);assert.equal(catalog.modules.length,241);assert(catalog.modules.some(x=>x.module==="infinite_pve"));assert(catalog.modules.some(x=>x.module==="charge"));assert(catalog.modules.some(x=>x.module==="hero_return"));assert(catalog.modules.some(x=>x.module==="act_limit_divine_pool"))});
test("generic system reducer persists battle, claims and settings deterministically",()=>{let state=initialState("infinite_pve");let result=reduceState(state,"start_battle",{});assert.equal(result.state.attempts,1);state=result.state;result=reduceState(state,"finish_battle",{score_delta:120,progress:3});assert.equal(result.state.score,120);assert.equal(result.state.progress,3);state=result.state;result=reduceState(state,"claim_reward",{claim_id:3});assert.equal(result.ok,true);assert.equal(reduceState(result.state,"claim_reward",{claim_id:3}).error,"reward_already_claimed")});
test("payment surface is sandbox signed and backed by official Charge config",()=>{const product=payments.skuInfo(0);assert(product);assert.equal(product.official_config,"Charge");assert.match(payments.signature("order"),/^[a-f0-9]{64}$/)});
test("instant recharge resolves visible ChargeGoods into direct resources",()=>{const goods=payments.goodsInfo(987600046);assert(goods);assert.equal(goods.charge_id,"2");assert.deepEqual(goods.rewards.map(row=>[row.item_id,row.amount]),[["item_999",10],["item_35",1],["vip_exp",60]]);const product=payments.purchaseInfo(null,987600057);assert.equal(product.goods_id,"987600057");assert(product.rewards.some(row=>row.type==="hero"&&row.id==="78"))});
