const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let token=sessionStorage.getItem('afkGmToken')||'',selectedPlayer=0,catalog=[];
async function api(path,options={}){const headers={'content-type':'application/json',...(options.headers||{})};if(token)headers.authorization=`Bearer ${token}`;const r=await fetch(path,{...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`${r.status}`);return data}
function showApp(){ $('#login').hidden=!!token;$('#content').hidden=!token;$('#logout').hidden=!token;if(token)loadDashboard() }
async function login(){try{const d=await api('/__afk/accounts/login',{method:'POST',body:JSON.stringify({username:$('#username').value,password:$('#password').value})});token=d.token;sessionStorage.setItem('afkGmToken',token);$('#loginError').textContent='';showApp()}catch(e){$('#loginError').textContent=e.message}}
async function health(){try{const h=await api('/__afk/health');$('#healthDot').classList.toggle('ok',h.ok&&h.db.ready);$('#healthText').textContent=h.db.ready?'全部服务正常':'数据库未就绪'}catch{$('#healthDot').classList.remove('ok');$('#healthText').textContent='服务离线'}}
async function loadDashboard(){const [h,e]=await Promise.all([api('/__afk/health'),api('/__afk/evidence')]);$('#metrics').innerHTML=[['数据库',h.db.ready?'就绪':'异常'],['协议模块',e.protocol.module_count],['正式配置',e.config.config_count],['战斗脚本',`${(e.battle.bytes/1048576).toFixed(1)} MiB`]].map(([k,v])=>`<div class="card metric"><span>${k}</span><strong>${v}</strong></div>`).join('');$('#evidence').textContent=JSON.stringify(e,null,2)}
async function loadPlayers(){const d=await api('/__afk/gm/players');const q=$('#playerSearch').value.toLowerCase();$('#playerRows').innerHTML=d.players.filter(p=>!q||JSON.stringify(p).toLowerCase().includes(q)).map(p=>`<tr><td>${p.id}</td><td><b>${p.nickname||'-'}</b><br><small>${p.player_uid}</small></td><td>${p.level}</td><td>${p.diamond}</td><td>${p.banned_until?'封禁':'正常'}</td><td><button data-player="${p.id}">选择</button></td></tr>`).join('');$$('[data-player]').forEach(b=>b.onclick=()=>{selectedPlayer=Number(b.dataset.player);$$('[data-player]').forEach(x=>x.classList.toggle('active',x===b))})}
async function runGm(){if(!selectedPlayer)return alert('请先选择玩家');let payload={};try{payload=JSON.parse($('#gmPayload').value||'{}')}catch{return alert('JSON 格式错误')}const d=await api('/__afk/gm/action',{method:'POST',body:JSON.stringify({player_id:selectedPlayer,action:$('#gmAction').value,...payload})});$('#gmResult').textContent=JSON.stringify(d,null,2);loadPlayers()}
async function loadSystems(){const d=await api('/__afk/systems/catalog');catalog=d.modules;renderSystems()}function renderSystems(){const q=$('#systemSearch').value.toLowerCase();$('#moduleGrid').innerHTML=catalog.filter(m=>m.module.includes(q)).map(m=>`<div class="module"><b>${m.module}</b><small>字段 ${m.request_field} · ${m.operations.length} 操作 · ${m.configs.length} 配置</small></div>`).join('')}
async function loadLiveops(){const d=await api('/__afk/liveops/instances');$('#liveopsList').innerHTML=d.instances.map(x=>`<div class="module"><b>${x.title}</b><small>${x.activity_key} · ${x.status}<br>${new Date(x.starts_at).toLocaleString()} — ${new Date(x.ends_at).toLocaleString()}</small></div>`).join('')||'<p class="muted">暂无实例</p>'}
async function loadOrders(){const d=await api('/__afk/gm/payments');$('#orders').innerHTML=`<pre>${JSON.stringify(d.orders,null,2)}</pre>`}async function loadAudit(){const d=await api('/__afk/gm/audit');$('#auditLog').textContent=JSON.stringify(d.records,null,2)}
const loaders={dashboard:loadDashboard,players:loadPlayers,systems:loadSystems,liveops:loadLiveops,payments:loadOrders,audit:loadAudit};$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.hidden=v.id!==b.dataset.view);$('#viewTitle').textContent=b.textContent;loaders[b.dataset.view]()});
$('#loginButton').onclick=login;$('#logout').onclick=()=>{token='';sessionStorage.removeItem('afkGmToken');showApp()};$('#refreshPlayers').onclick=loadPlayers;$('#playerSearch').oninput=loadPlayers;$('#runGmAction').onclick=runGm;$('#systemSearch').oninput=renderSystems;health();setInterval(health,15000);showApp();
